### ISSUE TITLE
Segfault with PHP 8.0 and 8.1 when `elastic_apm.capture_errors` is enabled

### ISSUE THREAD

**Issue by xyu** [elastic/apm-agent-php#1022]
**Describe the bug**

We run multiple PHP versions, namely7.4, 8.0, 8.1, and 8.2. It appears versions of the APM agent newer then 1.8.1 causes segfaults in PHP 8.0 and 8.1 in our environment. A core dump taken of one of the segfaults show the following:

```
(gdb) bt
#0  ZEND_FE_FETCH_R_SPEC_VAR_HANDLER () at /home/builder/php-8.0.29/Zend/zend_types.h:628
#1  0x000055c5c2a62bc0 in execute_ex (ex=0x50) at /home/builder/php-8.0.29/Zend/zend_vm_execute.h:57396
#2  0x000055c5c29f847a in zend_call_function (fci=<optimized out>, fci_cache=0x7ffeab2541e0) at /home/builder/php-8.0.29/Zend/zend_execute_API.c:895
#3  0x000055c5c29f8795 in _call_user_function_impl (object=object@entry=0x0, function_name=function_name@entry=0x7ffeab254300, retval_ptr=retval_ptr@entry=0x7ffeab254310, param_count=param_count@entry=4, params=params@entry=0x7ffeab254360,
    named_params=named_params@entry=0x0) at /home/builder/php-8.0.29/Zend/zend_execute_API.c:659
#4  0x00007f62fbee2b5b in callPhpFunction (phpFunctionName=..., argsCount=4, args=args@entry=0x7ffeab254360, consumeRetVal=consumeRetVal@entry=0x7f62fbee2a70 <consumeZvalRetVal>, consumeRetValCtx=consumeRetValCtx@entry=0x7ffeab2549e0)
    at /home/builder/apm-agent-php/util_for_PHP.c:202
#5  0x00007f62fbee402f in callPhpFunctionRetZval (phpFunctionName=..., argsCount=<optimized out>, args=args@entry=0x7ffeab254360, retVal=retVal@entry=0x7ffeab2549e0) at /home/builder/apm-agent-php/util_for_PHP.c:269
#6  0x00007f62fbee08bb in tracerPhpPartInternalFuncCallPreHook (interceptRegistrationId=interceptRegistrationId@entry=18, execute_data=execute_data@entry=0x7f62fc21e310) at /home/builder/apm-agent-php/tracer_PHP_part.c:234
#7  0x00007f62fbec272a in internalFunctionCallInterceptingImpl (interceptRegistrationId=<optimized out>, execute_data=0x7f62fc21e310, return_value=0x7ffeab254ab0) at /home/builder/apm-agent-php/elastic_apm_API.c:123
#8  0x000055c5c2a657b5 in ZEND_DO_ICALL_SPEC_RETVAL_UNUSED_HANDLER () at /home/builder/php-8.0.29/Zend/zend_vm_execute.h:1234
#9  execute_ex (ex=0x50) at /home/builder/php-8.0.29/Zend/zend_vm_execute.h:55159
#10 0x000055c5c2a69f54 in zend_execute (op_array=0x7f627307d500, return_value=0x0) at /home/builder/php-8.0.29/Zend/zend_vm_execute.h:59523
#11 0x000055c5c2a05553 in zend_execute_scripts (type=-64888816, type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /home/builder/php-8.0.29/Zend/zend.c:1694
#12 0x000055c5c29a4138 in php_execute_script (primary_file=<optimized out>) at /home/builder/php-8.0.29/main/main.c:2547
#13 0x000055c5c2783a4e in main (argc=<optimized out>, argv=<optimized out>) at /home/builder/php-8.0.29/sapi/fpm/fpm/fpm_main.c:2112
```

It appears the segfault happens when the [PHP function](https://github.com/elastic/apm-agent-php/blob/9010e462a277673b039a41964c0c1bb5750212a1/agent/php/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php#L140-L168) `internalFuncCallPreHook()` gets called.

**To Reproduce**
1. Build extension off latest main branch
2. Enable the APM extension in a PHP-FPM / PHP8.0 or PHP8.1 environment

**Comment by xyu** [comment]
I'm starting to take another look at this today and another interesting tidbit, it seems like there's maybe some bug or inconsistency when walking the backtrace array in PHP that's causing the segfault:

```
(gdb) zbacktrace
[0x7f1110816150] Elastic\Apm\Impl\Util\ArrayUtil->isList(array(32529)[0x7f11108161a0]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/Util/ArrayUtil.php:196
[0x7f1110815fc0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->getStackTraceFromPhpErrorData(array(5)[0x7f1110816010], "stackTrace") /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:403
[0x7f1110815e80] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->buildPhpErrorData(array(5)[0x7f1110815ed0]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:430
[0x7f1110815bf0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->ensureHaveLastPhpError(object[0x7f1110815c40]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:465
[0x7f1110815b40] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->ensureHaveLastErrorData(object[0x7f1110815b90]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:288
[0x7f1110815ad0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->Elastic\Apm\Impl\AutoInstrument\{closure}(object[0x7f1110815b20]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:271
[0x7f1110815a10] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->Elastic\Apm\Impl\AutoInstrument\{closure}(object[0x7f1110815a60]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:261
[0x7f1110815880] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->callAndSwallowThrowable("ensureHaveLatestDataDeferredByExtension", object[0x7f11108158e0]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:219
[0x7f11108157f0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->callWithTransactionForExtensionRequest("ensureHaveLatestDataDeferredByExtension", object[0x7f1110815850]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:262
[0x7f1110815780] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->ensureHaveLatestDataDeferredByExtension() /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:272
[0x7f11108153f0] Elastic\Apm\Impl\AutoInstrument\TransactionForExtensionRequest->onShutdown() /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php:376
[0x7f1110815380] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->Elastic\Apm\Impl\AutoInstrument\{closure}(object[0x7f11108153d0]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:478
[0x7f11108152c0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->Elastic\Apm\Impl\AutoInstrument\{closure}(object[0x7f1110815310]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:261
[0x7f1110815130] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->callAndSwallowThrowable("shutdown", object[0x7f1110815190]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:219
[0x7f11108150a0] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->callWithTransactionForExtensionRequest("shutdown", object[0x7f1110815100]) /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:262
[0x7f1110815020] Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->shutdown() /usr/local/share/elastic_apm/v1.9.1/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php:479
[0x7ffd7f6f28f0] ???
```

That might explain why we see this in PHP 8.0/8.1 but not 8.2

**Comment by xyu** [comment]
For now I have worked around this issue by turning off error capturing with

```
elastic_apm.capture_errors="off"
```

**Comment by SergeyKleyman** [comment]
@xyu Could you please test this scenario with the latest version ([v1.12.0](https://github.com/elastic/apm-agent-php/releases/tag/v1.12.0))? We made a couple fixes in the relevant code area after agents' v1.8.1.

**Comment by SergeyKleyman** [comment]
Closing it for now - please let us know if it's still relevant.
