### ISSUE TITLE
php-apm-agent - Call to undefined function Elastic\Apm\Impl\getmypid() error

### ISSUE THREAD

**Issue by mohammadalipour** [elastic/apm-agent-php#1025]
**Describe the bug**

- APM Server version (apm-server version): 8.7.2
- PHP-APM-agent 1.9.1 is installed on the php-alpine image (PHP version 8.1) on the AWS ECS 
and get this error :

`[Elastic APM PHP Tracer][CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable] Handling shutdown call let a throwable escape - skipping the rest of the steps. Error: Call to undefined function Elastic\Apm\Impl\getmypid()
`

and it's full error trace : 
`[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable] Handling shutdown call let a throwable escape - skipping the rest of the steps. Error: Call to undefined function Elastic\Apm\Impl\getmypid()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  Stack trace:
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #0 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/MetadataDiscoverer.php(86): Elastic\Apm\Impl\MetadataDiscoverer->discoverProcessData()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #1 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/Tracer.php(502): Elastic\Apm\Impl\MetadataDiscoverer->discover()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #2 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/Tracer.php(542): Elastic\Apm\Impl\Tracer->sendEventsToApmServer(Array, Array, Object(Elastic\Apm\Impl\BreakdownMetrics\PerTransaction), Object(Elastic\Apm\Impl\Transaction))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #3 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/Transaction.php(526): Elastic\Apm\Impl\Tracer->sendTransactionToApmServer(Object(Elastic\Apm\Impl\BreakdownMetrics\PerTransaction), Object(Elastic\Apm\Impl\Transaction))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #4 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php(391): Elastic\Apm\Impl\Transaction->end()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #5 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(478): Elastic\Apm\Impl\AutoInstrument\TransactionForExtensionRequest->onShutdown()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #6 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(261): Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::Elastic\Apm\Impl\AutoInstrument\{closure}(Object(Elastic\Apm\Impl\AutoInstrument\TransactionForExtensionRequest))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #7 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(219): Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::Elastic\Apm\Impl\AutoInstrument\{closure}(Object(Elastic\Apm\Impl\AutoInstrument\PhpPartFacade))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #8 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(262): Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::callAndSwallowThrowable('shutdown', Object(Closure))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #9 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(479): Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::callWithTransactionForExtensionRequest('shutdown', Object(Closure))
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #10 [internal function]: Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::shutdown()
[Elastic APM PHP Tracer] 2023-07-20 08:04:13.345281+00:00 [PID: 122] [TID: 122] [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:225] [callAndSwallowThrowable]  #10 [internal function]: Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::shutdown()`

**Comment by mohammadalipour** [comment]
I've figured out the root cause of the issue :
it's related to a security configuration that was set on the `php.ini` file, regarding this configuration `getmypid` was disabled and which caused problems with sending APM logs : 

`disable_functions = getmypid`

it should be removed and done  !
