### ISSUE TITLE
Doctrine breaks elastic apm

### ISSUE THREAD

**Issue by phumberdroz** [elastic/apm-agent-php#309]
**Describe the bug**
Enabling Elastic APM causes our API project to not respond anymore to request. (An exception is bubbled up)
```
[Tue Dec 01 11:10:21.950610 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/InterceptionManager.php:86 > elastic_apm_call_intercepted_original() expects parameter 1 to be string, object given
[Tue Dec 01 11:10:21.950706 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #0 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/InterceptionManager.php(86): elastic_apm_call_intercepted_original()
[Tue Dec 01 11:10:21.950902 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #1 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(138): Elastic\\Apm\\Impl\\AutoInstrument\\InterceptionManager->interceptedCall(1, 2, Object(Doctrine\\DBAL\\Driver\\PDOConnection), Array)
[Tue Dec 01 11:10:21.950948 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #2 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::interceptedCall(2, Object(Doctrine\\DBAL\\Driver\\PDOConnection), Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array)
[Tue Dec 01 11:10:21.950984 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #3 /opt/sFollowAPI/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array)
[Tue Dec 01 11:10:21.951050 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #4 /opt/sFollowAPI/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(904): Doctrine\\DBAL\\Driver\\PDOConnection->prepare(Object(Doctrine\\DBAL\\Query\\QueryBuilder))
[Tue Dec 01 11:10:21.951090 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #5 /opt/sFollowAPI/includes/Driver/PDORetryConnection.php(52): Doctrine\\DBAL\\Connection->executeQuery(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Array, NULL)
[Tue Dec 01 11:10:21.951134 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #6 /opt/sFollowAPI/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Spectrm\\sFollowAPI\\Driver\\PDORetryConnection->executeQuery(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Array)
[Tue Dec 01 11:10:21.951233 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #7 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Model/Model.php(685): Doctrine\\DBAL\\Connection->fetchAll(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array, Array)
[Tue Dec 01 11:10:21.951290 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #8 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Model/MySqlModel.php(21): Spectrm\\sAPI\\Model\\Model->fetchAll(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array)
[Tue Dec 01 11:10:21.951346 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #9 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Model/Model.php(417): Spectrm\\sAPI\\Model\\MySqlModel->fetchAll(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array)
[Tue Dec 01 11:10:21.951396 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #10 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Controller/Controller.php(418): Spectrm\\sAPI\\Model\\Model->selectList(Array, Array)
[Tue Dec 01 11:10:21.951467 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #11 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Controller/Controller.php(394): Spectrm\\sAPI\\Controller\\Controller->getRelatedDataFromModel(Array, Array)
[Tue Dec 01 11:10:21.951519 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #12 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Controller/Controller.php(336): Spectrm\\sAPI\\Controller\\Controller->getRelatedData(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), Array)
[Tue Dec 01 11:10:21.951573 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #13 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Controller/Controller.php(246): Spectrm\\sAPI\\Controller\\Controller->appendDependantData(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), Array)
[Tue Dec 01 11:10:21.951618 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #14 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/Controller/Controller.php(520): Spectrm\\sAPI\\Controller\\Controller->outputList(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), Array, Array, Array)
[Tue Dec 01 11:10:21.951663 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #15 /opt/sFollowAPI/vendor/symfony/http-kernel/HttpKernel.php(150): Spectrm\\sAPI\\Controller\\Controller->selectList(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended))
[Tue Dec 01 11:10:21.951718 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #16 /opt/sFollowAPI/vendor/symfony/http-kernel/HttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), 1)
[Tue Dec 01 11:10:21.951773 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #17 /opt/sFollowAPI/vendor/silex/silex/src/Silex/Application.php(496): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), 1, true)
[Tue Dec 01 11:10:21.951832 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #18 /opt/sFollowAPI/vendor/spectrm/sAPI/lib/SApi.php(463): Silex\\Application->handle(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended), 1, true)
[Tue Dec 01 11:10:21.951907 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #19 /opt/sFollowAPI/vendor/silex/silex/src/Silex/Application.php(477): Spectrm\\sAPI\\SApi->handle(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended))
[Tue Dec 01 11:10:21.951971 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #20 /opt/sFollowAPI/source/index.php(38): Silex\\Application->run(Object(Spectrm\\sFollowAPI\\DependencyInjection\\RequestExtended))
[Tue Dec 01 11:10:21.952053 2020] [php7:notice] [pid 16] [client 10.0.2.245:46760] WARN TypeError - #21 {main}
```

**To Reproduce**
1. Use this config '...'
2. Then call '....'
3. Then do '....'
(Currently working on an minimal example)

**Expected behavior**
Elastic APM not breaking our application (even if it is not working)

**Comment by SergeyKleyman** [comment]
Thank you for submitting this issue. Indeed we did not test on Doctrine. I don't have any experience with Doctrine so if you could provide a minimal example reproducing the issue it would definitely save us considerable effort to fix this bug.

**Comment by phumberdroz** [comment]
I am still on it.. It might be the issue is not related to doctrine. I am not a PHP software engineer so I have a Teammate looking into this more in depth at this moment
'

**Comment by phumberdroz** [comment]
What worked for us for now is disabling the automatic instrumentation of pdo span's
```
    sed -i '48 a return;' /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php
```

**Comment by science695** [comment]
Is that Doctrine using the ORM? or just DBAL(just wrapper around PDO)?

**Comment by phumberdroz** [comment]
We are just using the DBAL.

**Comment by jpcercal** [comment]
Hi there, together with @phumberdroz we were able to create a minimal example project in order to simulate the behavior, I hope it helps us to identify where's the problem. 

The PDO queries are working like a charm, however, when we try to fetch something with doctrine dbal using mysql_pdo as a driver (it's pottentially also happening for other drivers as we did not test it) with a where statement it fails:

```
$queryBuilder = $this->connection->createQueryBuilder();
        $queryBuilder->select('m.*')
            ->from('messages', 'm')
            ->where("m.id = ?");

return $this->connection->fetchAssoc($queryBuilder, [1]);
```

The repository below has more context on how to get it running. =)

You can take a look at it here:
https://github.com/jpcercal/elastic-apm-playground

**Comment by phumberdroz** [comment]
The current theory is that somewhere it is converted to a string in the php pdo extension and the same does not happen in this extension which is causing issue. A to String Cast ->__String() might be an easy fix but might sacrifice type safety.

At least this is my understanding of the issue after talking to a couple of engineers at work today.

**Comment by phumberdroz** [comment]
Hey @AlexanderWert,

how was this fixed? Or will this not get fixed?

**Comment by SergeyKleyman** [comment]
@phumberdroz I'm sorry for misunderstanding. I've reopened it and I will check what was actually fixed and I'll update.

**Comment by Kansukey** [comment]
Hello there,

Our team is reproducing the same issue. It seems to breaks all incoming request.
Do you plan to correct this problem soon? If so, do you have a timeline to share ?

Thanks a lot.

**Comment by SergeyKleyman** [comment]
@Kansukey Hi. Thank you for your feedback. We actively work on this issue and we will have an update very very soon.

**Comment by jpcercal** [comment]
Hey @Kansukey while the elastic team is working on a proper solution to fix the problem we created a temporary patch on our code to make it work. In case someone else is interested in a hack solution, below you will find what we did. Hopefully it also helps the elastic team to spot the issue and fix the problem. 😍 

As we figured out that the problem was happening on the where clauses when converting the query builder to a string it solves the issue, so first we created a custom PDO-MySQL-Driver class as shown below:

```
<?php

namespace OurAppNamespace\Driver;

use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\Driver as DriverInterface;
use Doctrine\DBAL\Driver\PDOException;
use Doctrine\DBAL\Driver\PDOMySql\Driver;

class PDOMysqlDriver extends Driver implements DriverInterface
{
    public function connect(array $params, $username = null, $password = null, array $driverOptions = [])
    {
        try {
            $conn = new PDOConnection(
                $this->constructPdoDsn($params),
                $username,
                $password,
                $driverOptions
            );
        } catch (PDOException $e) {
            throw DBALException::driverException($this, $e);
        }

        return $conn;
    }
}
```

After that, we created a custom PDOConnection implementation that's used by the `PDOMysqlDriver` class created above as follows (this is the instruction that makes it possible `$prepareString = (string)$prepareString;`):

```
<?php
namespace OurAppNamespace\Driver;

use Doctrine\DBAL\Driver\Connection;
use Doctrine\DBAL\Driver\PDOConnection as BasePDOConnection;
use Doctrine\DBAL\Driver\ServerInfoAwareConnection;
use Doctrine\DBAL\Query\QueryBuilder;

class PDOConnection extends BasePDOConnection implements Connection, ServerInfoAwareConnection
{
    public function prepare($prepareString, $driverOptions = [])
    {
        if ($prepareString instanceof QueryBuilder) {
            $prepareString = (string)$prepareString;
        }

        return parent::prepare($prepareString, $driverOptions);
    }
}
``` 

After that, we just need to say that the connection has to use the custom driver class. You can do it like this when setting up the connection with the database when using doctrine dbal:

```
<?php

use OurAppNamespace\Driver\PDOMysqlDriver;
use Doctrine\DBAL\DriverManager;

// ...

$connectionParams = [
    // ...
    'driverClass' => PDOMysqlDriver::class,
    // ...
];

$conn = DriverManager::getConnection($connectionParams);
```

You will find more info about the `driverClass` parameter on the doctrine DBAL documentation:
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#driver

I hope it helps. 🙏
