### ISSUE TITLE
elastic_apm.verify_server_cert seems not to be initialized when set to false

### ISSUE THREAD

**Issue by NicolaD77** [elastic/apm-agent-php#316]
When I set the value of **verify_server_cert** (as documented in https://www.elastic.co/guide/en/apm/agent/php/current/configuration-reference.html) to false it seems that the configuration does not load it

**To Reproduce**
1. my php.ini

[elastic_apm]
;
;; Elastic PHP APM Agent
;;
;; See: https://github.com/elastic/apm-agent-php
;;
extension = elastic_apm.so
elastic_apm.bootstrap_php_part_file=my-path/apm/apm-agent-php/src/bootstrap_php_part.php
;
;; Boolean flag to enable/disable all of the agent's functionality.
;; Possible values:
;; false = Disabled
;; true = Enabled
;; Default value: true
elastic_apm.enabled = true
;

**elastic_apm.verify_server_cert = false**

;; Location of the
;elastic_apm.log_file = "/var/log/directus/apm.log"
;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Monitored service ;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;
elastic_apm.environment = "production"
;
;; The required service's name to identify it later in the APM UI
;; Please change to a to your use case appropiate name.
elastic_apm.service_name="my-php-service"
;
;; Set the service's version to compare historical private between deployments
;; Default value: none
;elastic_apm.service_version = "1.1.1"
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Connection to APM Server ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;; URL to the APM Server
;; Default value: http://localhost:8200
;elastic_apm.server_url = "${APM_SERVER}"
elastic_apm.server_url=https://my-apm-server:8200
;
;; Secret token for the connection to APM Server
;; https://www.elastic.co/guide/en/apm/server/current/secure-communication-agents.html#secret-token
;; Default value: none
;elastic_apm.secret_token =

;;;;;;;;;;;;;;;;;;;;;;;;;
;; Supportability ;
;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;; Log level for syslog logging sink.
;; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
;; Default value: OFF
elastic_apm.log_level_syslog = ERROR
;
;; Log level for file logging sink.
;; Also see log_file option.
;; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
;; Default value: INFO
elastic_apm.log_level_file = ERROR
;
;; Log level for standard error stream logging sink.
;; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
;; Default value: OFF
elastic_apm.log_level_stderr = ERROR
;
;; Log level used as the default when the more specific log_level_* option is not set.
;;
;; For example with the following configuration:
;;
;; elastic_apm.log_level_syslog = INFO
;; elastic_apm.log_level_stderr =
;; elastic_apm.log_level = WARNING
;;
;; log levels are INFO for syslog and WARNING for stderr.
;;
;; Possible values: OFF, CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
;; Default value: none
elastic_apm.log_level = DEBUG

2.  If I check CONST initialization 

php -i | grep elastic |grep verify

I get:

elastic_apm.verify_server_cert =>  false =>
elastic_apm.verify_server_cert => no value => no value

3. If I restart php and navigate through my application the system stucks waiting for the timeout

Elastic APM PHP Tracer [PID: 1978] 2021-01-07 12:00:31.352668+01:00 [ERROR]    [Backend-Comm] [backend_comm.c:161] [sendEventsToApmServer] Sending events to APM Server failed. URL: ...

So I cannot use the agent on if my APM server is reachable via https.

Thank you

Nicola

**Comment by WolfangAukang** [comment]
I'm having a similar issue. Here are my settings:
```
extension=/opt/elastic/apm-agent-php/extensions/elastic_apm-20190902.so
[elastic_apm]
elastic_apm.bootstrap_php_part_file=/opt/elastic/apm-agent-php/src/bootstrap_php_part.php
elastic_apm.secret_token="token"
elastic_apm.enabled=true
elastic_apm.server_url=https://myurl.com:8200
elastic_apm.service_name="service"
elastic_apm.log_level=NOTICE
elastic_apm.verify_server_cert=false
```

This is what I get on the error logs (wasn't able to wrap it multiline):
```
2021-01-16 13:46:27.194059+00:00 [ERROR]    [Configuration] [Parser.php:78] [parse] Input raw config snapshot has a value but it's invalid - using default value. {"Option name":"verify_server_cert","Option default value":true,"Exception":{"type":"Elastic\\Apm\\Impl\\Config\\ParseException","value_as_string":"Elastic\\Apm\\Impl\\Config\\ParseException: Not a valid bool value. Raw option value: `' in \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/EnumOptionParser.php:108\nStack trace:\n#0 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(43): Elastic\\Apm\\Impl\\Config\\EnumOptionParser->parse()\n#1 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(68): Elastic\\Apm\\Impl\\Config\\Parser::parseOptionRawValue()\n#2 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(120): Elastic\\Apm\\Impl\\Config\\Parser->parse()\n#3 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(73): Elastic\\Apm\\Impl\\Tracer->buildConfig()\n#4 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/TracerBuilder.php(74): Elastic\\Apm\\Impl\\Tracer->__construct()\n#5 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/GlobalTracerHolder.php(29): Elastic\\Apm\\Impl\\TracerBuilder->build()\n#6 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(198): Elastic\\Apm\\Impl\\GlobalTracerHolder::get()\n#7 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(42): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::buildTracer()\n#8 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(86): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade->__construct()\n#9 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::bootstrap()\n#10 {main}"},"namespace":"Elastic\\Apm\\Impl\\Config","class":"Parser","stacktrace":[{"class":"Elastic\\Apm\\Impl\\Log\\Backend","function":"log","file":"EnabledLoggerProxy.php","line":61,"this":{"type":"Elastic\\Apm\\Impl\\Log\\Backend","object_ID":10,"object_hash":"0000000006f9d0d3000000007dc04f92"},"args":[2,"Input raw config snapshot has a value but it's invalid - using default value",{"Option name":"verify_server_cert","Option default value":true,"Exception":{"type":"Elastic\\Apm\\Impl\\Config\\ParseException","value_as_string":"Elastic\\Apm\\Impl\\Config\\ParseException: Not a valid bool value. Raw option value: `' in \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/EnumOptionParser.php:108\nStack trace:\n#0 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(43): Elastic\\Apm\\Impl\\Config\\EnumOptionParser->parse()\n#1 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(68): Elastic\\Apm\\Impl\\Config\\Parser::parseOptionRawValue()\n#2 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(120): Elastic\\Apm\\Impl\\Config\\Parser->parse()\n#3 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(73): Elastic\\Apm\\Impl\\Tracer->buildConfig()\n#4 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/TracerBuilder.php(74): Elastic\\Apm\\Impl\\Tracer->__construct()\n#5 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/GlobalTracerHolder.php(29): Elastic\\Apm\\Impl\\TracerBuilder->build()\n#6 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(198): Elastic\\Apm\\Impl\\GlobalTracerHolder::get()\n#7 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(42): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::buildTracer()\n#8 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(86): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade->__construct()\n#9 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::bootstrap()\n#10 {main}"}},78,"parse",{"category":"Configuration","namespace":"Elastic\\Apm\\Impl\\Config","fqClassName":"Elastic\\Apm\\Impl\\Config\\Parser","srcCodeFile":"\/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php","inheritedData":null,"context":[],"backend":{}},null,1]},{"class":"Elastic\\Apm\\Impl\\Log\\EnabledLoggerProxy","function":"log","file":"Parser.php","line":84,"this":{"type":"Elastic\\Apm\\Impl\\Log\\EnabledLoggerProxy","object_ID":43,"object_hash":"0000000006f9d0f2000000007dc04f92"},"args":["Input raw config snapshot has a value but it's invalid - using default value",{"Option name":"verify_server_cert","Option default value":true,"Exception":{"type":"Elastic\\Apm\\Impl\\Config\\ParseException","value_as_string":"Elastic\\Apm\\Impl\\Config\\ParseException: Not a valid bool value. Raw option value: `' in \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/EnumOptionParser.php:108\nStack trace:\n#0 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(43): Elastic\\Apm\\Impl\\Config\\EnumOptionParser->parse()\n#1 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Config\/Parser.php(68): Elastic\\Apm\\Impl\\Config\\Parser::parseOptionRawValue()\n#2 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(120): Elastic\\Apm\\Impl\\Config\\Parser->parse()\n#3 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(73): Elastic\\Apm\\Impl\\Tracer->buildConfig()\n#4 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/TracerBuilder.php(74): Elastic\\Apm\\Impl\\Tracer->__construct()\n#5 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/GlobalTracerHolder.php(29): Elastic\\Apm\\Impl\\TracerBuilder->build()\n#6 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(198): Elastic\\Apm\\Impl\\GlobalTracerHolder::get()\n#7 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(42): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::buildTracer()\n#8 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(86): Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade->__construct()\n#9 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::bootstrap()\n#10 {main}"}}]},{"class":"Elastic\\Apm\\Impl\\Config\\Parser","function":"parse","file":"Tracer.php","line":120,"this":{"type":"Elastic\\Apm\\Impl\\Config\\Parser","object_ID":12,"object_hash":"0000000006f9d0d5000000007dc04f92"},"args":[{"enabled":{"parser":{"dbgEnumDesc":"bool","nameValuePairs":[["true",true],["yes",true],["on",true],["1",true],["false",false],["no",false],["off",false],["0",false]],"isCaseSensitive":false,"isUnambiguousPrefixAllowed":false},"defaultValue":true},"environment":{"parser":[]},"log_level":{"parser":{"dbgEnumDesc":"log level","nameValuePairs":[["OFF",0],["CRITICAL",1],["ERROR",2],["WARNING",3],["NOTICE",4],["INFO",5],["DEBUG",6],["TRACE",7]],"isCaseSensitive":false,"isUnambiguousPrefixAllowed":true}},"log_level_stderr":{"parser":{"dbgEnumDesc":"log level","nameValuePairs":[["OFF",0],["CRITICAL",1],["ERROR",2],["WARNING",3],["NOTICE",4],["INFO",5],["DEBUG",6],["TRACE",7]],"isCaseSensitive":false,"isUnambiguousPrefixAllowed":true}},"log_level_syslog":{"parser":{"dbgEnumDesc":"log level","nameValuePairs":[["OFF",0],["CRITICAL",1],["ERROR",2],["WARNING",3],["NOTICE",4],["INFO",5],["DEBUG",6],["TRACE",7]],"isCaseSensitive":false,"isUnambiguousPrefixAllowed":true}},"server_timeout":{"parser":{"minValidValueInMilliseconds":0,"maxValidValueInMilliseconds":null,"defaultUnits":1},"defaultValue":30000},"service_name":{"parser":[]},"service_version":{"parser":[]},"transaction_max_spans":{"parser":{"minValidValue":0,"maxValidValue":null},"defaultValue":500},"transaction_sample_rate":{"parser":{"minValidValue":0,"maxValidValue":1},"defaultValue":1},"verify_server_cert":{"parser":{"dbgEnumDesc":"bool","nameValuePairs":[["true",true],["yes",true],["on",true],["1",true],["false",false],["no",false],["off",false],["0",false]],"isCaseSensitive":false,"isUnambiguousPrefixAllowed":false},"defaultValue":true}},{"type":"Elastic\\Apm\\Impl\\Config\\CompositeRawSnapshot","object_ID":40,"object_hash":"0000000006f9d0f1000000007dc04f92"}]},{"class":"Elastic\\Apm\\Impl\\Tracer","function":"buildConfig","file":"Tracer.php","line":73,"this":{"isRecording":true,"providedDependencies":{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null},"config":null},"args":[]},{"class":"Elastic\\Apm\\Impl\\Tracer","function":"__construct","file":"TracerBuilder.php","line":74,"this":{"isRecording":true,"providedDependencies":{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null},"config":null},"args":[{"clock":null,"configRawSnapshotSource":null,"eventSink":null,"logSink":null}]},{"class":"Elastic\\Apm\\Impl\\TracerBuilder","function":"build","file":"GlobalTracerHolder.php","line":29,"this":{"type":"Elastic\\Apm\\Impl\\TracerBuilder","object_ID":3,"object_hash":"0000000006f9d0da000000007dc04f92"},"args":[]},{"class":"Elastic\\Apm\\Impl\\GlobalTracerHolder","function":"get","file":"PhpPartFacade.php","line":198,"args":[]},{"class":"Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade","function":"buildTracer","file":"PhpPartFacade.php","line":42,"args":[]},{"class":"Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade","function":"__construct","file":"PhpPartFacade.php","line":86,"this":{"type":"Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade","object_ID":1,"object_hash":"0000000006f9d0d8000000007dc04f92"},"args":[1610804787185859]},{"class":"Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade","function":"bootstrap","args":[4,1610804787185859]}]}
```

**Comment by NicolaD77** [comment]
Hello, Any news about this issue?

**Comment by SergeyKleyman** [comment]
Hi @NicolaD77 - I’ll take a look at it ASAP.

**Comment by siddjain** [comment]
Hello, we are using https://github.com/elastic/apm-agent-php/releases/download/v1.1/apm-agent-php_1.1_all.apk and it seems the issue is still there in it. we get this output after setting `elastic_apm.verify_server_cert=false` in .ini file:

```
elastic_apm.verify_server_cert => no value => no value
```

**Comment by AshanCG** [comment]
We are also still observing same issue with  https://github.com/elastic/apm-agent-php/releases/tag/v1.3 (v1.3).

After setting 
_elastic_apm.verify_server_cert = false_ in /etc/php/7.4/apache2/conf.d/99-elastic-apm-custom.ini (php 7.4 -  Ubuntu 20.x), we get following error :

```
php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
elastic_apm
exif
...........


2021-10-03 11:26:07.489078+05:30 [ERROR]    [Backend-Comm] [backend_comm.c:169] [sendEventsToApmServer] Sending events to APM Server failed. URL: `https://x..x.x.x:8200/intake/v2/events'. 
Error message: `SSL peer certificate or SSH remote key was not OK'
```

**Comment by tobiasz-gleba** [comment]
issue still exists on debian php-apm-v1.4.2

**Comment by alexadavid** [comment]
problem still exist on php-amp-v1.6.2-1.noarch.rpm

after setting 
`elastic_apm.verify_server_cert = 0`

I get 
```
php -i | grep elastic |grep verify

[Elastic APM PHP Tracer] 2022-12-12 09:40:06.198806+01:00 [PID: 19192] [TID: 19192] [ERROR]    [Backend-Comm] [backend_comm.c:252] [syncSendEventsToApmServer] Sending events to APM Server failed. URL: `https://xxxxx.xx/intake/v2/events'. Error message: `SSL peer certificate or SSH remote key was not OK'. Current process command line: `php -i'

elastic_apm.verify_server_cert => 0 => 0 => 0
elastic_apm.verify_server_cert => 0 => 0
```
