### ISSUE TITLE
Crashes with Matomo (Symfony based)

### ISSUE THREAD

**Issue by mikkeschiren** [elastic/apm-agent-php#427]
**Describe the bug**
When enabled things seems to crash badly:

```
127.0.0.1 -  09/Jun/2021:20:35:05 +0000 "GET /index.php" 200
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown] One of the steps in shutdown sequence let a throwable escape - skipping the rest of the steps. Error_yamlizearrayCall to undefined method Elastic\Apm\Impl\Transaction:: has no query with handle '()
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown]     Stack trace:
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown]     #0 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(221): Elastic\Apm\Impl\AutoInstrument\TransactionForExtensionRequest->onShutdown()
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown]     #1 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php(204): Elastic\Apm\Impl\AutoInstrument\PhpPartFacade->shutdownImpl()
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown]     #2 [internal function]: Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::shutdown()
2021-06-09 20:35:07.657028+00:00 [CRITICAL] [Bootstrap] [BootstrapStageLogger.php:209] [shutdown]     #3 {main}
127.0.0.1 -  09/Jun/2021:20:35:05 +0000 "GET /index.php" 200
[09-Jun-2021 20:36:19 UTC] Error in Matomo: Call to undefined method Piwik\SettingsPiwik::isHttpsForced()
127.0.0.1 -  09/Jun/2021:20:36:19 +0000 "GET /index.php" 500
```

**To Reproduce**
Version used: v1.1
Config used:

```
elastic_apm.secret_token=verysecrettoken42
elastic_apm.enabled=true
elastic_apm.server_url=http://my-server:8200
elastic_apm.service_name=MySite
elastic_apm.bootstrap_php_part_file=/opt/elastic/apm-agent-php/src/bootstrap_php_part.php
elastic_apm.transaction_max_spans=5000
elastic_apm.service_name=AF
elastic_apm.log_level=TRACE
elastic_apm.log_level_stderr=WARNING
elastic_apm.log_level_syslog=TRACE
elastic_apm.server_timeout=30s
elastic_apm.service_version=v.0.1
elastic_apm.environment=staging
elastic_apm.transaction_max_spans=2000
elastic_apm.transaction_sample_rate=1.0
elastic_apm.verify_server_cert=false
```

**Comment by SergeyKleyman** [comment]
We are going to close it for now. Please let us know if it's relevant.
