### ISSUE TITLE
TypeError: strncmp(): Argument #3 ($length) must be of type int, null given src/ElasticApm/Impl/AutoInstrument/Autoloader.php:54

### ISSUE THREAD

**Issue by sakarikl** [elastic/apm-agent-php#817]
TypeError: strncmp(): Argument #3 ($length) must be of type int, null given in /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/Autoloader.php:54

Relevant stack trace 

Stack trace:
#0 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/Autoloader.php(54): strncmp()
#1 /opt/elastic/apm-agent-php/src/ElasticApm/Impl/AutoInstrument/Autoloader.php(63): Elastic\Apm\Impl\AutoInstrument\Autoloader::shouldAutoloadCodeForClass()
#2 [internal function]: Elastic\Apm\Impl\AutoInstrument\Autoloader::autoloadCodeForClass()

PHP 8.1.12

**Comment by sakarikl** [comment]
This is something rare. It has come up 24 times in 3 days with more than a million request.

**Comment by SergeyKleyman** [comment]
@sakarikl Could you please check if this issue is still reproducible with the latest agent release?

**Comment by sakarikl** [comment]
There was no known way to reproduce this and Elastic APM is no longer running on those servers that generated these errors.
