### ISSUE TITLE
postHook has let a Throwable to escape

### ISSUE THREAD

**Issue by GHostlyFOX** [elastic/apm-agent-php#912]
After updating to the latest version, they started getting an error from console handlers.

```
[Elastic APM PHP Tracer] 2023-04-03 10:52:12.316000+06:00 [PID: 44076] [TID: 44076] [ERROR]    [Interception] [InterceptionManager.php:178] [interceptedCallPostHook] postHook has let a Throwable to escape {"throwable":{"type":"Elastic\\Apm\\Impl\\BackendComm\\SerializationException","value_as_string":"Elastic\\Apm\\Impl\\Util\\JsonException: json_encode() failed. json_last_error_msg(): Malformed UTF-8 characters, possibly incorrectly encoded. dataType: Elastic\\Apm\\Impl\\Span in \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Util\/JsonUtil.php:49\nStack trace:\n#0 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/BackendComm\/SerializationUtil.php(55): Elastic\\Apm\\Impl\\Util\\JsonUtil::encode(Object(Elastic\\Apm\\Impl\\Span))\n#1 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/BackendComm\/EventSender.php(114): Elastic\\Apm\\Impl\\BackendComm\\SerializationUtil::serializeAsJson(Object(Elastic\\Apm\\Impl\\Span))\n#2 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(486): Elastic\\Apm\\Impl\\BackendComm\\EventSender->consume(Object(Elastic\\Apm\\Impl\\Metadata), Array, Array, NULL, NULL)\n#3 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(500): Elastic\\Apm\\Impl\\Tracer->sendEventsToApmServer(Array, Array, NULL, NULL)\n#4 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Span.php(271): Elastic\\Apm\\Impl\\Tracer->sendSpanToApmServer(Object(Elastic\\Apm\\Impl\\Span))\n#5 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/Util\/AutoInstrumentationUtil.php(83): Elastic\\Apm\\Impl\\Span->endSpanEx(5, NULL)\n#6 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/Util\/AutoInstrumentationUtil.php(117): Elastic\\Apm\\Impl\\AutoInstrument\\Util\\AutoInstrumentationUtil::endSpan(3, Object(Elastic\\Apm\\Impl\\Span), false, true)\n#7 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/InterceptionManager.php(173): Elastic\\Apm\\Impl\\AutoInstrument\\Util\\AutoInstrumentationUtil::Elastic\\Apm\\Impl\\AutoInstrument\\Util\\{closure}(2, false, true)\n#8 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(186): Elastic\\Apm\\Impl\\AutoInstrument\\InterceptionManager->interceptedCallPostHook(1, false, true)\n#9 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::interceptedCallPostHook(false, true)\n#10 \/home\/bitrix\/core\/modules\/main\/lib\/db\/mysqliconnection.php(135): mysqli->query('INSERT INTO `ec...', 0)\n#11 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(327): Bitrix\\Main\\DB\\MysqliConnection->queryInternal('INSERT INTO `ec...', Array, NULL)\n#12 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(376): Bitrix\\Main\\DB\\Connection->query('INSERT INTO `ec...', NULL)\n#13 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(451): Bitrix\\Main\\DB\\Connection->queryExecute('INSERT INTO `ec...')\n#14 \/home\/bitrix\/core\/modules\/main\/lib\/orm\/data\/datamanager.php(937): Bitrix\\Main\\DB\\Connection->add('ecc_order_trace', Array, 'ID')\n#15 \/home\/bitrix\/www\/local\/modules\/ecc.order\/lib\/helpers\/rejectorderhelper.php(730): Bitrix\\Main\\ORM\\Data\\DataManager::add(Array)\n#16 \/home\/bitrix\/www\/local\/modules\/ecc.order\/lib\/helpers\/rejectorderhelper.php(285): Ecc\\Order\\Helpers\\RejectOrderHelper->saveJsonTrace(1736446)\n#17 \/home\/bitrix\/www\/local\/modules\/ecc.cli\/lib\/cliautorejectorder.php(105): Ecc\\Order\\Helpers\\RejectOrderHelper->reject()\n#18 \/home\/bitrix\/www\/local\/modules\/ecc.cli\/lib\/cliautorejectorder.php(59): Ecc\\Cli\\CliAutoRejectOrder->autoReject(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Command\/Command.php(299): Ecc\\Cli\\CliAutoRejectOrder->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(978): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(Ecc\\Cli\\CliAutoRejectOrder), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 \/home\/bitrix\/www\/local\/cli\/console(170): Symfony\\Component\\Console\\Application->run()\n#24 {main}\n\nNext Elastic\\Apm\\Impl\\BackendComm\\SerializationException: Serialization failed. JsonUtil::encode() failed. {\"$jsonEncodable type\":\"array\",\"causedBy\":{\"type\":\"Elastic\\\\Apm\\\\Impl\\\\Util\\\\JsonException\",\"value_as_string\":\"Elastic\\\\Apm\\\\Impl\\\\Util\\\\JsonException: json_encode() failed. json_last_error_msg(): Malformed UTF-8 characters, possibly incorrectly encoded. dataType: array in \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Util\\\/JsonUtil.php:49\\nStack trace:\\n#0 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Log\\\/LoggableToEncodedJson.php(63): Elastic\\\\Apm\\\\Impl\\\\Util\\\\JsonUtil::encode(Array, true)\\n#1 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Log\\\/LoggableToString.php(51): Elastic\\\\Apm\\\\Impl\\\\Log\\\\LoggableToEncodedJson::convert(Object(Elastic\\\\Apm\\\\Impl\\\\Log\\\\AdhocLoggableObject), true, 1000)\\n#2 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Util\\\/ExceptionUtil.php(60): Elastic\\\\Apm\\\\Impl\\\\Log\\\\LoggableToString::convert(Object(Elastic\\\\Apm\\\\Impl\\\\Log\\\\AdhocLoggableObject), true)\\n#3 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/BackendComm\\\/SerializationUtil.php(58): Elastic\\\\Apm\\\\Impl\\\\Util\\\\ExceptionUtil::buildMessage('Serialization f...', Array)\\n#4 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/BackendComm\\\/EventSender.php(114): Elastic\\\\Apm\\\\Impl\\\\BackendComm\\\\SerializationUtil::serializeAsJson(Object(Elastic\\\\Apm\\\\Impl\\\\Span))\\n#5 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Tracer.php(486): Elastic\\\\Apm\\\\Impl\\\\BackendComm\\\\EventSender->consume(Object(Elastic\\\\Apm\\\\Impl\\\\Metadata), Array, Array, NULL, NULL)\\n#6 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Tracer.php(500): Elastic\\\\Apm\\\\Impl\\\\Tracer->sendEventsToApmServer(Array, Array, NULL, NULL)\\n#7 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/Span.php(271): Elastic\\\\Apm\\\\Impl\\\\Tracer->sendSpanToApmServer(Object(Elastic\\\\Apm\\\\Impl\\\\Span))\\n#8 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/AutoInstrument\\\/Util\\\/AutoInstrumentationUtil.php(83): Elastic\\\\Apm\\\\Impl\\\\Span->endSpanEx(5, NULL)\\n#9 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/AutoInstrument\\\/Util\\\/AutoInstrumentationUtil.php(117): Elastic\\\\Apm\\\\Impl\\\\AutoInstrument\\\\Util\\\\AutoInstrumentationUtil::endSpan(3, Object(Elastic\\\\Apm\\\\Impl\\\\Span), false, true)\\n#10 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/AutoInstrument\\\/InterceptionManager.php(173): Elastic\\\\Apm\\\\Impl\\\\AutoInstrument\\\\Util\\\\AutoInstrumentationUtil::Elastic\\\\Apm\\\\Impl\\\\AutoInstrument\\\\Util\\\\{closure}(2, false, true)\\n#11 \\\/opt\\\/elastic\\\/apm-agent-php\\\/src\\\/ElasticApm\\\/Impl\\\/AutoInstrument\\\/PhpPartFacade.php(186): Elastic\\\\Apm\\\\Impl\\\\AutoInstrument\\\\InterceptionManager->interceptedCallPostHook(1, false, true)\\n#12 [internal function]: Elastic\\\\Apm\\\\Impl\\\\AutoInstrument\\\\PhpPartFacade::interceptedCallPostHook(false, true)\\n#13 \\\/home\\\/bitrix\\\/core\\\/modules\\\/main\\\/lib\\\/db\\\/mysqliconnection.php(135): mysqli->query('INSERT INTO `ec...', 0)\\n#14 \\\/home\\\/bitrix\\\/core\\\/modules\\\/main\\\/lib\\\/db\\\/connection.php(327): Bitrix\\\\Main\\\\DB\\\\MysqliConnection->queryInternal('INSERT INTO `ec...', Array, NULL)\\n#15 \\\/home\\\/bitrix\\\/core\\\/modules\\\/main\\\/lib\\\/db\\\/connection.php(376): Bitrix\\\\Main\\\\DB\\\\Connection->query('INSERT INTO `ec...', NULL)\\n#16 \\\/home\\\/bitrix\\\/core\\\/modules\\\/main\\\/lib\\\/db\\\/connection.php(451): Bitrix\\\\Main\\\\DB\\\\Connection->queryExecute('INSERT INTO `ec...')\\n#17 \\\/home\\\/bitrix\\\/core\\\/modules\\\/main\\\/lib\\\/orm\\\/data\\\/datamanager.php(937): Bitrix\\\\Main\\\\DB\\\\Connection->add('ecc_order_trace', Array, 'ID')\\n#18 \\\/home\\\/bitrix\\\/www\\\/local\\\/modules\\\/ecc.order\\\/lib\\\/helpers\\\/rejectorderhelper.php(730): Bitrix\\\\Main\\\\ORM\\\\Data\\\\DataManager::add(Array)\\n#19 \\\/home\\\/bitrix\\\/www\\\/local\\\/modules\\\/ecc.order\\\/lib\\\/helpers\\\/rejectorderhelper.php(285): Ecc\\\\Order\\\\Helpers\\\\RejectOrderHelper->saveJsonTrace(1736446)\\n#20 \\\/home\\\/bitrix\\\/www\\\/local\\\/modules\\\/ecc.cli\\\/lib\\\/cliautorejectorder.php(105): Ecc\\\\Order\\\\Helpers\\\\RejectOrderHelper->reject()\\n#21 \\\/home\\\/bitrix\\\/www\\\/local\\\/modules\\\/ecc.cli\\\/lib\\\/cliautorejectorder.php(59): Ecc\\\\Cli\\\\CliAutoRejectOrder->autoReject(Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#22 \\\/home\\\/bitrix\\\/core\\\/yii\\\/vendor\\\/symfony\\\/console\\\/Command\\\/Command.php(299): Ecc\\\\Cli\\\\CliAutoRejectOrder->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#23 \\\/home\\\/bitrix\\\/core\\\/yii\\\/vendor\\\/symfony\\\/console\\\/Application.php(978): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#24 \\\/home\\\/bitrix\\\/core\\\/yii\\\/vendor\\\/symfony\\\/console\\\/Application.php(295): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(Ecc\\\\Cli\\\\CliAutoRejectOrder), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#25 \\\/home\\\/bitrix\\\/core\\\/yii\\\/vendor\\\/symfony\\\/console\\\/Application.php(167): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#26 \\\/home\\\/bitrix\\\/www\\\/local\\\/cli\\\/console(170): Symfony\\\\Component\\\\Console\\\\Application->run()\\n#27 {main}\"}} in \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/BackendComm\/SerializationUtil.php:57\nStack trace:\n#0 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/BackendComm\/EventSender.php(114): Elastic\\Apm\\Impl\\BackendComm\\SerializationUtil::serializeAsJson(Object(Elastic\\Apm\\Impl\\Span))\n#1 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(486): Elastic\\Apm\\Impl\\BackendComm\\EventSender->consume(Object(Elastic\\Apm\\Impl\\Metadata), Array, Array, NULL, NULL)\n#2 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Tracer.php(500): Elastic\\Apm\\Impl\\Tracer->sendEventsToApmServer(Array, Array, NULL, NULL)\n#3 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/Span.php(271): Elastic\\Apm\\Impl\\Tracer->sendSpanToApmServer(Object(Elastic\\Apm\\Impl\\Span))\n#4 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/Util\/AutoInstrumentationUtil.php(83): Elastic\\Apm\\Impl\\Span->endSpanEx(5, NULL)\n#5 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/Util\/AutoInstrumentationUtil.php(117): Elastic\\Apm\\Impl\\AutoInstrument\\Util\\AutoInstrumentationUtil::endSpan(3, Object(Elastic\\Apm\\Impl\\Span), false, true)\n#6 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/InterceptionManager.php(173): Elastic\\Apm\\Impl\\AutoInstrument\\Util\\AutoInstrumentationUtil::Elastic\\Apm\\Impl\\AutoInstrument\\Util\\{closure}(2, false, true)\n#7 \/opt\/elastic\/apm-agent-php\/src\/ElasticApm\/Impl\/AutoInstrument\/PhpPartFacade.php(186): Elastic\\Apm\\Impl\\AutoInstrument\\InterceptionManager->interceptedCallPostHook(1, false, true)\n#8 [internal function]: Elastic\\Apm\\Impl\\AutoInstrument\\PhpPartFacade::interceptedCallPostHook(false, true)\n#9 \/home\/bitrix\/core\/modules\/main\/lib\/db\/mysqliconnection.php(135): mysqli->query('INSERT INTO `ec...', 0)\n#10 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(327): Bitrix\\Main\\DB\\MysqliConnection->queryInternal('INSERT INTO `ec...', Array, NULL)\n#11 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(376): Bitrix\\Main\\DB\\Connection->query('INSERT INTO `ec...', NULL)\n#12 \/home\/bitrix\/core\/modules\/main\/lib\/db\/connection.php(451): Bitrix\\Main\\DB\\Connection->queryExecute('INSERT INTO `ec...')\n#13 \/home\/bitrix\/core\/modules\/main\/lib\/orm\/data\/datamanager.php(937): Bitrix\\Main\\DB\\Connection->add('ecc_order_trace', Array, 'ID')\n#14 \/home\/bitrix\/www\/local\/modules\/ecc.order\/lib\/helpers\/rejectorderhelper.php(730): Bitrix\\Main\\ORM\\Data\\DataManager::add(Array)\n#15 \/home\/bitrix\/www\/local\/modules\/ecc.order\/lib\/helpers\/rejectorderhelper.php(285): Ecc\\Order\\Helpers\\RejectOrderHelper->saveJsonTrace(1736446)\n#16 \/home\/bitrix\/www\/local\/modules\/ecc.cli\/lib\/cliautorejectorder.php(105): Ecc\\Order\\Helpers\\RejectOrderHelper->reject()\n#17 \/home\/bitrix\/www\/local\/modules\/ecc.cli\/lib\/cliautorejectorder.php(59): Ecc\\Cli\\CliAutoRejectOrder->autoReject(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Command\/Command.php(299): Ecc\\Cli\\CliAutoRejectOrder->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#19 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(978): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#20 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand(Object(Ecc\\Cli\\CliAutoRejectOrder), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/home\/bitrix\/core\/yii\/vendor\/symfony\/console\/Application.php(167): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/home\/bitrix\/www\/local\/cli\/console(170): Symfony\\Component\\Console\\Application->run()\n#23 {main}"},"namespace":"Elastic\\Apm\\Impl\\AutoInstrument","class":"InterceptionManager","interceptRegistrationId":19,"interceptRegistration":{"interceptedCallDescription":"mysqli::query","plugin":{"index":0,"description":"BUILT-IN"}},"stacktrace":[{"file":"InterceptionManager.php","line":181,"class":"InterceptionManager","function":"interceptedCallPostHook"},{"file":"PhpPartFacade.php","line":186,"class":"PhpPartFacade","function":"interceptedCallPostHook"},{"class":"mysqli","function":"query"},{"file":"mysqliconnection.php","line":135,"class":"MysqliConnection","function":"queryInternal"},{"file":"connection.php","line":327,"class":"Connection","function":"query"},{"file":"connection.php","line":376,"class":"Connection","function":"queryExecute"},{"file":"connection.php","line":451,"class":"Connection","function":"add"},{"file":"datamanager.php","line":937,"class":"DataManager","function":"add"},{"file":"rejectorderhelper.php","line":730,"class":"RejectOrderHelper","function":"saveJsonTrace"},{"file":"rejectorderhelper.php","line":285,"class":"RejectOrderHelper","function":"reject"},{"file":"cliautorejectorder.php","line":105,"class":"CliAutoRejectOrder","function":"autoReject"},{"file":"cliautorejectorder.php","line":59,"class":"CliAutoRejectOrder","function":"execute"},{"file":"Command.php","line":299,"class":"Command","function":"run"},{"file":"Application.php","line":978,"class":"Application","function":"doRunCommand"},{"file":"Application.php","line":295,"class":"Application","function":"doRun"},{"file":"Application.php","line":167,"class":"Application","function":"run"},{"file":"console","line":170}]}
```

**Comment by intuibase** [comment]
@SergeyKleyman please revisit it

**Comment by SergeyKleyman** [comment]
@GHostlyFOX  [v1.12.0 release](https://github.com/elastic/apm-agent-php/releases/tag/v1.12.0) includes the fix for this issue. Please try it out.

**Comment by SergeyKleyman** [comment]
Closing it - please let us know if it's still relevant.
